spring.data.mongodb.uri=mongodb+srv://Egresados:Egresados2023@cluster0.oqvbdt5.mongodb.net/
spring.data.mongodb.database=Egresados
server.port= 8080
spring.jackson.default-property-inclusion=NON_NULL

# security
jwt.secret=secretkeyforproyectegresadoscorhuilafacultadings
jwt.expiration=36000

# Config SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.username=egresadoscorhuila.proyect@gmail.com
spring.mail.password=ucntozawjzjxxhjr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
